on: 
  push:
    branches:
      - deleloper
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v2
    
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username}}
        password: ${{ secrets.ftp_password }}
        server-dir: public_html/development
        
        protocolo : ftps 
        port : 21 

        # exclude: |
        #   **/.git*
        #   **/.git*/**
        #   **/node_modules/**
        #   fileToExclude.txt

        # exclude: '
        #   - **/vendor/**
        #   - **/vendor*/**
        #   - **/node_modules/**
        #   - **/node_modules*/**
        #   - **/resource/css/**
        #   - **/resource/css*/**
        #   - **/resource/js/**
        #   - **/resource/js*/**
        #   - **/.git/**
        #   - **/.git*/**
        #   '
        
        # exclude: .github** .github*/** node_modules** node_modules*/** resources/js** resources/js*/** resources/css** resources/css*/** resources/sass* resources/sass*/** Workspace* Workspace*/** .vscode* .vscode*/** .gitignore* .gitignore*/**  .gitattributes* .gitattributes*/**



         